// Everything Antigravity-specific that is not a file layout: the plugin
// manifest, the MCP configuration, the hooks.json and the guard adapter that
// runs a Claude Code plugin's PreToolUse hooks inside Antigravity, and a
// structural check of the result.
//
// What was proven on a real machine (Antigravity desktop app and the `agy` CLI
// 1.2.17, Windows, 05/10/2026) and shapes this file:
// - a plugin in ~/.gemini/config/plugins/<dir>/ is loaded by the app AND by agy;
// - hooks.json hooks run in both, from the plugin's own folder (cmd /c on
//   Windows), fed {toolCall: {name, args}, conversationId, transcriptPath, ...};
// - "deny" blocks the call, even under agy --dangerously-skip-permissions;
//   "ask" opens the app's permission dialog with our reason;
// - an empty object {} is read as a DENY: a hook with no opinion must print
//   nothing at all;
// - plugin MCP servers load, renamed <plugin>_<server> by Antigravity.

import fs from "node:fs";
import path from "node:path";
import { frontmatterFields } from "./targets/codex-check.mjs";

/** plugin.json keys the loader reads (author/homepage are silently dropped). */
const MANIFEST_KEYS = new Set(["name", "displayName", "version", "description", "logo", "suggestedPrompts", "disabled"]);

/** Antigravity manifest for a converted plugin. */
export function antigravityManifest(src, { defaultPrompt = [], version } = {}) {
  let prompts = defaultPrompt.length ? defaultPrompt : (src.manifest.interface?.defaultPrompt || src.manifest.defaultPrompt || []);
  if (!Array.isArray(prompts)) prompts = [prompts];
  prompts = prompts.map((s) => String(s).trim()).filter(Boolean).slice(0, 3);
  return {
    name: src.name,
    displayName: src.displayName,
    version: version || src.version,
    description: src.description,
    ...(prompts.length ? { suggestedPrompts: prompts } : {}),
  };
}

/** Claude Code's .mcp.json -> Antigravity's mcp_config.json (remote servers use `serverUrl`). */
export function mcpForAntigravity(mcpJson) {
  const out = {};
  for (const [name, s] of Object.entries(mcpJson?.mcpServers ?? {})) {
    if (!s || typeof s !== "object") continue;
    if (s.url) out[name] = { serverUrl: s.url, ...(s.headers ? { headers: s.headers } : {}) };
    else if (s.command) out[name] = { command: s.command, ...(s.args ? { args: s.args } : {}), ...(s.env ? { env: s.env } : {}) };
  }
  return Object.keys(out).length ? { mcpServers: out } : null;
}

/** Claude Code tool names -> the Antigravity tools that do the same thing. */
const CLAUDE_TO_ANTIGRAVITY = { Bash: ["run_command"], Read: ["view_file"], Write: ["write_to_file"] };
/** Claude Code tools with no counterpart to guard in Antigravity: left out without a word. */
const CLAUDE_ONLY_TOOLS = new Set(["Monitor", "BashOutput", "KillShell", "Task", "TodoWrite", "ExitPlanMode", "NotebookEdit"]);

/** Files of the source that only Claude Code reads; the Antigravity port has its own. */
export const CLAUDE_ONLY_FILES = new Set([".claude-plugin/plugin.json", ".mcp.json", "hooks/hooks.json", "hooks/opencode.permission.json"]);

/**
 * The Antigravity matcher for a list of Claude Code matchers, and the Claude
 * tools left without an equivalent (reported, not ported).
 */
export function antigravityMatcher(matchers) {
  const tools = new Set();
  const unmapped = new Set();
  for (const m of matchers) {
    if (!m || m === "*") return { matcher: "*", unmapped: [] };
    for (const name of m.split("|").map((s) => s.trim()).filter(Boolean)) {
      const mapped = CLAUDE_TO_ANTIGRAVITY[name];
      if (mapped) mapped.forEach((t) => tools.add(t)); else if (!CLAUDE_ONLY_TOOLS.has(name)) unmapped.add(name);
    }
  }
  return { matcher: [...tools].join("|"), unmapped: [...unmapped] };
}

export const GUARD_FILE = "hooks/antigravity-guard.mjs";

/** hooks.json for the plugin: one named hook that runs the generated adapter. */
export function antigravityHooksJson(name, hooks) {
  const { matcher } = antigravityMatcher(hooks.map((h) => h.matcher));
  if (!matcher) return null;
  const timeout = Math.max(10, hooks.reduce((s, h) => s + (h.timeout || 60), 0) + 5);
  return {
    [`${name}-guard`]: {
      PreToolUse: [{ matcher, hooks: [{ type: "command", command: `node ${GUARD_FILE}`, timeout }] }],
    },
  };
}

/**
 * The adapter Antigravity runs before a tool call. It translates Antigravity's
 * payload into the one Claude Code feeds its hooks, runs the plugin's own hook
 * commands unchanged, and answers in Antigravity's terms. Standalone: it finds
 * the plugin folder from its own location, so the same file works installed
 * by hand or unzipped from a bundle.
 */
export function renderAntigravityGuard({ name, hooks, generator }) {
  return `// ${GUARD_FILE} - generated by ${generator} on ${new Date().toISOString().slice(0, 10)}.
// Runs the Claude Code PreToolUse hooks of the plugin "${name}" inside
// Antigravity: same hook commands, fed the JSON Claude Code feeds them. A
// "deny" blocks the tool call, an "ask" opens Antigravity's permission dialog
// with the hook's reason. No opinion = no output at all (Antigravity reads an
// empty object as a refusal). Fails open, like the hooks it runs.
// Regenerate with the converter instead of editing this file.
import path from "node:path";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";

const NAME = ${JSON.stringify(name)};
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const HOOKS = ${JSON.stringify(hooks, null, 2)};
// Antigravity tool names -> the names Claude Code hooks match on.
const CLAUDE_TOOL_NAMES = { run_command: "Bash", view_file: "Read", write_to_file: "Write" };

function readStdin() {
  return new Promise((resolve) => {
    let text = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (c) => (text += c));
    process.stdin.on("end", () => resolve(text));
    process.stdin.on("error", () => resolve(text));
  });
}

function run(hook, payload) {
  const command = hook.command.split("\${CLAUDE_PLUGIN_ROOT}").join(ROOT);
  return new Promise((resolve) => {
    let stdout = "";
    let stderr = "";
    let done = false;
    const finish = (r) => { if (!done) { done = true; resolve(r); } };
    let child;
    try {
      child = spawn(command, {
        shell: true,
        env: { ...process.env, CLAUDE_PLUGIN_ROOT: ROOT, CLAUDE_PROJECT_DIR: payload.cwd },
        windowsHide: true,
      });
    } catch (e) {
      return finish({ error: String(e) });
    }
    const timer = setTimeout(() => { try { child.kill(); } catch {} finish({ error: "timeout" }); }, (hook.timeout || 60) * 1000);
    child.stdout.on("data", (c) => (stdout += c));
    child.stderr.on("data", (c) => (stderr += c));
    child.on("error", (e) => { clearTimeout(timer); finish({ error: String(e) }); });
    child.on("close", (code) => { clearTimeout(timer); finish({ code, stdout, stderr }); });
    child.stdin.on("error", () => {});
    child.stdin.end(JSON.stringify(payload));
  });
}

/** A Claude Code hook result: JSON decision, or exit code 2 = block. */
function decisionOf(result) {
  if (result.error) return null;
  if (result.code === 2) return { decision: "deny", reason: (result.stderr || "blocked by hook").trim() };
  const text = (result.stdout || "").trim();
  if (!text) return null;
  try {
    const out = JSON.parse(text);
    const h = out.hookSpecificOutput;
    if (h?.permissionDecision === "deny" || h?.permissionDecision === "ask") {
      return { decision: h.permissionDecision, reason: h.permissionDecisionReason || "" };
    }
    if (out.decision === "block") return { decision: "deny", reason: out.reason || "" };
  } catch {}
  return null;
}

async function main() {
  let input;
  try { input = JSON.parse(await readStdin()); } catch { return; }
  const tool = input?.toolCall?.name ?? "";
  const toolName = CLAUDE_TOOL_NAMES[tool] ?? tool;
  const matching = HOOKS.filter((h) => !h.matcher || h.matcher === "*" || new RegExp(\`^(?:\${h.matcher})$\`).test(toolName));
  if (!matching.length) return;
  const args = input.toolCall.args ?? {};
  const cwd = args.Cwd || (Array.isArray(input.workspacePaths) && input.workspacePaths[0]) || process.cwd();
  const toolInput = toolName === "Bash"
    ? { command: args.CommandLine ?? "", description: args.toolSummary ?? "" }
    : toolName === "Read" ? { file_path: args.AbsolutePath ?? args.path ?? "" }
    : toolName === "Write" ? { file_path: args.TargetFile ?? args.path ?? "", content: args.CodeContent ?? "" }
    : args;
  const payload = {
    session_id: input.conversationId ?? "",
    transcript_path: input.transcriptPath ?? "",
    cwd,
    hook_event_name: "PreToolUse",
    tool_name: toolName,
    tool_input: toolInput,
  };
  let worst = null;
  for (const hook of matching) {
    const d = decisionOf(await run(hook, payload));
    if (d && (!worst || (worst.decision === "ask" && d.decision === "deny"))) worst = d;
  }
  if (!worst) return;
  // Hooks often sign their own reasons ("[Hypervibe] ..."); do not sign twice.
  const reason = /^\\s*\\[/.test(worst.reason) ? worst.reason : \`[\${NAME}] \${worst.reason}\`;
  process.stdout.write(JSON.stringify({ decision: worst.decision, reason }));
}

main().catch(() => {});
`;
}

/** Errors found in the Antigravity plugin at `root` (empty array = passes). */
export function checkAntigravityPlugin(root) {
  const errors = [];
  let manifest;
  try {
    manifest = JSON.parse(fs.readFileSync(path.join(root, "plugin.json"), "utf8"));
  } catch (e) {
    return [e.code === "ENOENT" ? "missing `plugin.json`" : "`plugin.json` must be valid JSON"];
  }
  for (const k of Object.keys(manifest)) if (!MANIFEST_KEYS.has(k)) errors.push(`plugin.json field \`${k}\` is ignored by Antigravity`);
  if (typeof manifest.name !== "string" || !/^[a-zA-Z0-9_-]+$/.test(manifest.name)) errors.push("plugin.json field `name` must match ^[a-zA-Z0-9_-]+$");
  if (manifest.suggestedPrompts !== undefined && (!Array.isArray(manifest.suggestedPrompts) || manifest.suggestedPrompts.length > 3)) {
    errors.push("plugin.json field `suggestedPrompts` must be a list of at most 3 prompts");
  }
  for (const [file, check] of [["hooks.json", null], ["mcp_config.json", "mcpServers"]]) {
    const p = path.join(root, file);
    if (!fs.existsSync(p)) continue;
    try {
      const j = JSON.parse(fs.readFileSync(p, "utf8"));
      if (check && (!j[check] || typeof j[check] !== "object")) errors.push(`\`${file}\` must hold a \`${check}\` object`);
    } catch { errors.push(`\`${file}\` must be valid JSON`); }
  }
  const skillsRoot = path.join(root, "skills");
  if (fs.existsSync(skillsRoot)) {
    for (const d of fs.readdirSync(skillsRoot, { withFileTypes: true })) {
      if (!d.isDirectory() || d.name.startsWith(".")) continue;
      const file = path.join(skillsRoot, d.name, "SKILL.md");
      if (!fs.existsSync(file)) { errors.push(`skill \`${d.name}\` is missing \`SKILL.md\``); continue; }
      const { error, fields } = frontmatterFields(fs.readFileSync(file, "utf8"));
      if (error) { errors.push(`skill \`${d.name}\` ${error}`); continue; }
      if (!fields.name || !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(fields.name)) errors.push(`skill \`${d.name}\`: \`name\` must be lowercase and hyphenated`);
      if (!fields.description) errors.push(`skill \`${d.name}\`: \`description\` must be non-empty`);
    }
  }
  return errors;
}
