// Renders the OpenCode plugin that ports a Claude Code plugin's PreToolUse
// command hooks. It runs the very same hook scripts, fed the very same JSON,
// so the plugin author keeps a single decision function for every host. It
// can also carry the plugin's MCP servers and permission rules into OpenCode's
// configuration through the `config` hook, so a drop-in install needs no
// edit of opencode.json at all.

/**
 * @param {object} p
 * @param {string} p.name         plugin name
 * @param {{kind:"absolute", path:string} | {kind:"home", rel:string}} p.root
 *        where the plugin lives: a baked absolute path, or a path under the
 *        user's home resolved when the plugin loads (portable bundles)
 * @param {Array<{matcher:string, command:string, timeout:number}>} p.hooks
 * @param {"soft"|"pass"} p.askMode   what to do with an `ask` decision
 * @param {object} [p.mcp]            OpenCode `mcp` entries to inject (absent keys only)
 * @param {object} [p.permission]     OpenCode permission fragment to inject (absent patterns only)
 * @param {string} p.generator        tool name + version, for the header
 */
export function renderGuardPlugin({ name, root, hooks, askMode, mcp = {}, permission = null, generator }) {
  const rootExpr = root.kind === "home"
    ? `path.join(os.homedir(), ...${JSON.stringify(root.rel.split("/").filter(Boolean))})`
    : JSON.stringify(root.path);
  const injects = Object.keys(mcp).length > 0 || (permission && Object.keys(permission).length > 0);
  return `// ${name}-guard.js - generated by ${generator} on ${new Date().toISOString().slice(0, 10)}.
// Ports the Claude Code PreToolUse hooks of the plugin "${name}" to OpenCode:
// the same hook commands run, fed the same JSON Claude Code feeds them, and a
// "deny" decision blocks the tool call (the model reads the reason).${injects ? `
// It also carries the plugin's MCP servers and permission rules into OpenCode's
// configuration when it loads, without touching opencode.json.` : ""}
// Regenerate with the converter instead of editing this file.
import os from "node:os";
import path from "node:path";
import { spawn } from "node:child_process";

const NAME = ${JSON.stringify(name)};
const ROOT = ${rootExpr};
const HOOKS = ${JSON.stringify(hooks, null, 2)};
// "soft": an \`ask\` decision blocks the call once with the reason and asks the
//         model to get the user's explicit agreement, then lets the identical
//         command through on its next attempt in the same session.
// "pass": an \`ask\` decision is left to OpenCode's own permission rules.
const ASK_MODE = ${JSON.stringify(askMode)};
const MCP = ${JSON.stringify(mcp, null, 2)};
const PERMISSION = ${JSON.stringify(permission ?? {}, null, 2)};

// OpenCode tool ids -> the names Claude Code hooks match on.
const CLAUDE_TOOL_NAMES = {
  bash: "Bash", edit: "Edit", write: "Write", read: "Read", glob: "Glob", grep: "Grep",
  webfetch: "WebFetch", websearch: "WebSearch", task: "Task", skill: "Skill", question: "AskUserQuestion",
};

const pending = new Map(); // "sessionID\\ncommand" -> true once the user was asked

function run(hook, payload) {
  const command = hook.command.split("\${CLAUDE_PLUGIN_ROOT}").join(ROOT);
  return new Promise((resolve) => {
    let stdout = "";
    let stderr = "";
    let done = false;
    const finish = (r) => { if (!done) { done = true; resolve(r); } };
    let child;
    try {
      child = spawn(command, {
        shell: true,
        env: { ...process.env, CLAUDE_PLUGIN_ROOT: ROOT, CLAUDE_PROJECT_DIR: payload.cwd },
        windowsHide: true,
      });
    } catch (e) {
      return finish({ error: String(e) });
    }
    const timer = setTimeout(() => { try { child.kill(); } catch {} finish({ error: "timeout" }); }, (hook.timeout || 60) * 1000);
    child.stdout.on("data", (c) => (stdout += c));
    child.stderr.on("data", (c) => (stderr += c));
    child.on("error", (e) => { clearTimeout(timer); finish({ error: String(e) }); });
    child.on("close", (code) => { clearTimeout(timer); finish({ code, stdout, stderr }); });
    child.stdin.on("error", () => {});
    child.stdin.end(JSON.stringify(payload));
  });
}

/** Reads a Claude Code hook result: JSON decision, or exit code 2 = block. */
function decisionOf(result) {
  if (result.error) return null; // fail open, like the hook itself
  if (result.code === 2) return { decision: "deny", reason: (result.stderr || "blocked by hook").trim() };
  const text = (result.stdout || "").trim();
  if (!text) return null;
  try {
    const out = JSON.parse(text);
    const h = out.hookSpecificOutput;
    if (h?.permissionDecision === "deny" || h?.permissionDecision === "ask") {
      return { decision: h.permissionDecision, reason: h.permissionDecisionReason || "" };
    }
    if (out.decision === "block") return { decision: "deny", reason: out.reason || "" };
  } catch {}
  return null;
}

/** Adds what the plugin needs to OpenCode's configuration, never replacing
 *  what the user already wrote (a bare "bash": "allow" is widened first). */
function inject(cfg) {
  if (!cfg || typeof cfg !== "object") return;
  if (Object.keys(MCP).length) {
    cfg.mcp ??= {};
    for (const [key, def] of Object.entries(MCP)) if (!(key in cfg.mcp)) cfg.mcp[key] = def;
  }
  for (const [tool, rules] of Object.entries(PERMISSION)) {
    cfg.permission ??= {};
    if (typeof rules === "string") { if (!(tool in cfg.permission)) cfg.permission[tool] = rules; continue; }
    let existing = cfg.permission[tool];
    if (typeof existing === "string") existing = { "*": existing };
    if (!existing || typeof existing !== "object") existing = {};
    for (const [pattern, action] of Object.entries(rules)) if (!(pattern in existing)) existing[pattern] = action;
    cfg.permission[tool] = existing;
  }
}

export const Guard = async ({ directory }) => ({
  config: async (cfg) => { inject(cfg); },
  "tool.execute.before": async (input, output) => {
    const toolName = CLAUDE_TOOL_NAMES[input.tool] ?? input.tool;
    const matching = HOOKS.filter((h) => !h.matcher || new RegExp(\`^(?:\${h.matcher})$\`).test(toolName));
    if (!matching.length) return;
    const args = output?.args ?? {};
    const toolInput = toolName === "Bash" ? { command: args.command, description: args.description, timeout: args.timeout } : args;
    const payload = {
      session_id: input.sessionID,
      transcript_path: "",
      cwd: directory,
      hook_event_name: "PreToolUse",
      tool_name: toolName,
      tool_input: toolInput,
      tool_use_id: input.callID,
    };
    let worst = null;
    for (const hook of matching) {
      const d = decisionOf(await run(hook, payload));
      if (d && (!worst || (worst.decision === "ask" && d.decision === "deny"))) worst = d;
    }
    if (!worst) return;
    // Hooks often sign their own reasons ("[Hypervibe] ..."); do not sign twice.
    const reason = /^\\s*\\[/.test(worst.reason) ? worst.reason : \`[\${NAME}] \${worst.reason}\`;
    if (worst.decision === "deny") throw new Error(reason);
    if (ASK_MODE !== "soft") return;
    const key = \`\${input.sessionID}\\n\${typeof toolInput.command === "string" ? toolInput.command : JSON.stringify(toolInput)}\`;
    if (pending.get(key)) { pending.delete(key); return; }
    pending.set(key, true);
    throw new Error(
      \`\${reason}\\n\\nThis command needs the user's explicit confirmation in the conversation. Ask them, and once they have agreed, run exactly the same command again.\`,
    );
  },
});
`;
}
