// Renders the OpenCode plugin that ports a Claude Code plugin's PreToolUse
// command hooks. It runs the very same hook scripts, fed the very same JSON,
// so the plugin author keeps a single decision function for every host.

/**
 * @param {object} p
 * @param {string} p.name       plugin name
 * @param {string} p.root       absolute install root (forward slashes)
 * @param {Array<{matcher:string, command:string, timeout:number}>} p.hooks
 * @param {"soft"|"pass"} p.askMode  what to do with an `ask` decision
 * @param {string} p.generator  tool name + version, for the header
 */
export function renderGuardPlugin({ name, root, hooks, askMode, generator }) {
  return `// ${name}-guard.js - generated by ${generator} on ${new Date().toISOString().slice(0, 10)}.
// Ports the Claude Code PreToolUse hooks of the plugin "${name}" to OpenCode:
// the same hook commands run, fed the same JSON Claude Code feeds them, and a
// "deny" decision blocks the tool call (the model reads the reason).
// Regenerate with the converter instead of editing this file.
import { spawn } from "node:child_process";

const NAME = ${JSON.stringify(name)};
const ROOT = ${JSON.stringify(root)};
const HOOKS = ${JSON.stringify(hooks, null, 2)};
// "soft": an \`ask\` decision blocks the call once with the reason and asks the
//         model to get the user's explicit agreement, then lets the identical
//         command through on its next attempt in the same session.
// "pass": an \`ask\` decision is left to OpenCode's own permission rules
//         (see the permission fragment merged into opencode.json).
const ASK_MODE = ${JSON.stringify(askMode)};

// OpenCode tool ids -> the names Claude Code hooks match on.
const CLAUDE_TOOL_NAMES = {
  bash: "Bash", edit: "Edit", write: "Write", read: "Read", glob: "Glob", grep: "Grep",
  webfetch: "WebFetch", websearch: "WebSearch", task: "Task", skill: "Skill", question: "AskUserQuestion",
};

const pending = new Map(); // "sessionID\\ncommand" -> true once the user was asked

function run(hook, payload) {
  const command = hook.command.split("\${CLAUDE_PLUGIN_ROOT}").join(ROOT);
  return new Promise((resolve) => {
    let stdout = "";
    let stderr = "";
    let done = false;
    const finish = (r) => { if (!done) { done = true; resolve(r); } };
    let child;
    try {
      child = spawn(command, {
        shell: true,
        env: { ...process.env, CLAUDE_PLUGIN_ROOT: ROOT, CLAUDE_PROJECT_DIR: payload.cwd },
        windowsHide: true,
      });
    } catch (e) {
      return finish({ error: String(e) });
    }
    const timer = setTimeout(() => { try { child.kill(); } catch {} finish({ error: "timeout" }); }, (hook.timeout || 60) * 1000);
    child.stdout.on("data", (c) => (stdout += c));
    child.stderr.on("data", (c) => (stderr += c));
    child.on("error", (e) => { clearTimeout(timer); finish({ error: String(e) }); });
    child.on("close", (code) => { clearTimeout(timer); finish({ code, stdout, stderr }); });
    child.stdin.on("error", () => {});
    child.stdin.end(JSON.stringify(payload));
  });
}

/** Reads a Claude Code hook result: JSON decision, or exit code 2 = block. */
function decisionOf(result) {
  if (result.error) return null; // fail open, like the hook itself
  if (result.code === 2) return { decision: "deny", reason: (result.stderr || "blocked by hook").trim() };
  const text = (result.stdout || "").trim();
  if (!text) return null;
  try {
    const out = JSON.parse(text);
    const h = out.hookSpecificOutput;
    if (h?.permissionDecision === "deny" || h?.permissionDecision === "ask") {
      return { decision: h.permissionDecision, reason: h.permissionDecisionReason || "" };
    }
    if (out.decision === "block") return { decision: "deny", reason: out.reason || "" };
  } catch {}
  return null;
}

export const Guard = async ({ directory }) => ({
  "tool.execute.before": async (input, output) => {
    const toolName = CLAUDE_TOOL_NAMES[input.tool] ?? input.tool;
    const matching = HOOKS.filter((h) => !h.matcher || new RegExp(\`^(?:\${h.matcher})$\`).test(toolName));
    if (!matching.length) return;
    const args = output?.args ?? {};
    const toolInput = toolName === "Bash" ? { command: args.command, description: args.description, timeout: args.timeout } : args;
    const payload = {
      session_id: input.sessionID,
      transcript_path: "",
      cwd: directory,
      hook_event_name: "PreToolUse",
      tool_name: toolName,
      tool_input: toolInput,
      tool_use_id: input.callID,
    };
    let worst = null;
    for (const hook of matching) {
      const d = decisionOf(await run(hook, payload));
      if (d && (!worst || (worst.decision === "ask" && d.decision === "deny"))) worst = d;
    }
    if (!worst) return;
    // Hooks often sign their own reasons ("[Hypervibe] ..."); do not sign twice.
    const reason = /^\\s*\\[/.test(worst.reason) ? worst.reason : \`[\${NAME}] \${worst.reason}\`;
    if (worst.decision === "deny") throw new Error(reason);
    if (ASK_MODE !== "soft") return;
    const key = \`\${input.sessionID}\\n\${typeof toolInput.command === "string" ? toolInput.command : JSON.stringify(toolInput)}\`;
    if (pending.get(key)) { pending.delete(key); return; }
    pending.set(key, true);
    throw new Error(
      \`\${reason}\\n\\nThis command needs the user's explicit confirmation in the conversation. Ask them, and once they have agreed, run exactly the same command again.\`,
    );
  },
});
`;
}
