// The installer every bundle carries, so a converted plugin can update itself
// from inside the host with nothing but Node: unpack the new bundle anywhere,
// then run the installer it contains.
//
//   node <unpacked>/<plugin dir>/.claude-plugin-to-codex.install.mjs --from <unpacked>
//
// The rendered script is standalone (no import of this package): it runs on
// machines where the converter was never installed. It is kept free of
// backticks and of dollar-brace sequences so it can live in a raw template.

export const INSTALLER_FILE = ".claude-plugin-to-codex.install.mjs";

const TEMPLATE = String.raw`#!/usr/bin/env node
// Installer of the converted plugin __NAME__ for __HOST__, generated by __GENERATOR__.
//
// Installs or updates this plugin from an unpacked bundle, from inside the host:
//   node <unpacked>/__BUNDLE_PLUGIN__/.claude-plugin-to-codex.install.mjs --from <unpacked>
//
// The installed copy moves to ~/.claude-plugin-to-codex/backups (outside every
// folder the host scans, so it is never loaded twice), the new copy takes its
// place, and the old one comes back if any step fails. When the bundle was
// unpacked straight into its final place, only the registration step runs.
//
// Flags: --from <dir> (required), --home <dir> (default: the user's home),
//        --no-refresh (Codex: do not ask Codex to reinstall).
// Prints one JSON line. Exit code 0 on success, 1 otherwise.
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";

const TARGET = __TARGET__;
const NAME = __NAME_JSON__;
const MARKER = ".claude-plugin-to-codex.json";
const KEEP_BACKUPS = 3;

const argv = process.argv.slice(2);
const opt = (flag) => {
  const i = argv.indexOf(flag);
  return i >= 0 && argv[i + 1] !== undefined ? argv[i + 1] : null;
};
const done = (result, code) => {
  process.stdout.write(JSON.stringify(result) + "\n");
  process.exitCode = code;
};
const readJson = (p) => {
  try { return JSON.parse(fs.readFileSync(p, "utf8")); } catch { return null; }
};
const same = (a, b) => {
  const x = path.resolve(a), y = path.resolve(b);
  return process.platform === "win32" ? x.toLowerCase() === y.toLowerCase() : x === y;
};

function layout(home) {
  if (TARGET === "codex") {
    return {
      bundlePlugin: path.join("plugins", NAME),
      pluginDir: path.join(home, "plugins", NAME),
      bundleMarketplace: path.join(".agents", "plugins", "marketplace.json"),
      marketplace: path.join(home, ".agents", "plugins", "marketplace.json"),
    };
  }
  const config = path.join(home, ".config", "opencode");
  return {
    bundlePlugin: path.join("skills", NAME),
    pluginDir: path.join(config, "skills", NAME),
    bundleGuard: path.join("plugins", NAME + "-guard.js"),
    guard: path.join(config, "plugins", NAME + "-guard.js"),
  };
}

/** A rename, or a copy when the two folders sit on different volumes. */
function move(from, to) {
  fs.mkdirSync(path.dirname(to), { recursive: true });
  try {
    fs.renameSync(from, to);
  } catch (e) {
    if (e.code !== "EXDEV") throw e;
    fs.cpSync(from, to, { recursive: true });
    fs.rmSync(from, { recursive: true, force: true });
  }
}

/** Lists the plugin in Codex's personal marketplace, keeping every other entry. */
function registerCodex(from, L) {
  const bundled = readJson(path.resolve(from, L.bundleMarketplace));
  const entry = bundled && Array.isArray(bundled.plugins) ? bundled.plugins.find((p) => p && p.name === NAME) : null;
  if (!entry) throw new Error("the bundle does not list " + NAME + " in .agents/plugins/marketplace.json");
  let mk;
  if (fs.existsSync(L.marketplace)) {
    mk = readJson(L.marketplace);
    if (!mk || typeof mk !== "object") throw new Error("cannot read " + L.marketplace + " (left untouched)");
  } else {
    mk = { name: bundled.name || "personal", interface: bundled.interface || { displayName: "Personal" }, plugins: [] };
  }
  if (!Array.isArray(mk.plugins)) mk.plugins = [];
  const i = mk.plugins.findIndex((p) => p && p.name === NAME);
  if (i >= 0) mk.plugins[i] = Object.assign({}, mk.plugins[i], { source: entry.source });
  else mk.plugins.push(entry);
  fs.mkdirSync(path.dirname(L.marketplace), { recursive: true });
  fs.writeFileSync(L.marketplace, JSON.stringify(mk, null, 2) + "\n");
  return mk.name || "personal";
}

/** The Codex CLI: config, PATH, then where the desktop apps keep it. */
function codexBinary(home) {
  const candidates = [];
  try {
    const cfg = fs.readFileSync(path.join(process.env.CODEX_HOME || path.join(home, ".codex"), "config.toml"), "utf8");
    const m = cfg.match(/CODEX_CLI_PATH\s*=\s*['"]([^'"]+)['"]/);
    if (m) candidates.push(m[1]);
  } catch {}
  candidates.push("codex");
  if (process.platform === "win32") {
    const bin = path.join(process.env.LOCALAPPDATA || path.join(home, "AppData", "Local"), "OpenAI", "Codex", "bin");
    try {
      fs.readdirSync(bin)
        .map((d) => path.join(bin, d, "codex.exe"))
        .filter((p) => fs.existsSync(p))
        .sort((a, b) => fs.statSync(b).mtimeMs - fs.statSync(a).mtimeMs)
        .forEach((p) => candidates.push(p));
    } catch {}
  }
  if (process.platform === "darwin") candidates.push("/Applications/Codex.app/Contents/Resources/codex");
  for (const bin of candidates) {
    if (bin !== "codex" && !fs.existsSync(bin)) continue;
    const r = spawnSync(bin, ["--version"], { encoding: "utf8", timeout: 30000, shell: bin === "codex" && process.platform === "win32" });
    if (r.status === 0) return bin;
  }
  return null;
}

/** Codex loads skills from its own cache: reinstalling is what refreshes it. */
function refreshCodex(home, marketplaceName) {
  const bin = codexBinary(home);
  if (!bin) return { status: "codex-not-found", hint: "In Codex, open /plugins and install " + NAME + " again." };
  const selector = NAME + "@" + marketplaceName;
  const run = (args) => spawnSync(bin, args, { encoding: "utf8", timeout: 180000, shell: bin === "codex" && process.platform === "win32" });
  let r = run(["plugin", "add", selector]);
  let text = ((r.stdout || "") + (r.stderr || "")).trim();
  if (r.status !== 0 && /already/i.test(text)) {
    run(["plugin", "remove", selector]);
    r = run(["plugin", "add", selector]);
    text = ((r.stdout || "") + (r.stderr || "")).trim();
  }
  return r.status === 0
    ? { status: "done", detail: text.slice(-300) }
    : { status: "failed", detail: text.slice(-300), hint: "In Codex, open /plugins and install " + NAME + " again." };
}

function pruneBackups(root) {
  let entries;
  try { entries = fs.readdirSync(root, { withFileTypes: true }); } catch { return; }
  const mine = entries
    .filter((e) => e.isDirectory() && e.name.startsWith(TARGET + "-" + NAME + "-"))
    .map((e) => ({ dir: path.join(root, e.name), t: fs.statSync(path.join(root, e.name)).mtimeMs }))
    .sort((a, b) => b.t - a.t);
  for (const old of mine.slice(KEEP_BACKUPS)) fs.rmSync(old.dir, { recursive: true, force: true });
}

function main() {
  const from = opt("--from");
  if (!from) return done({ ok: false, error: "missing --from <unpacked bundle>" }, 1);
  const home = path.resolve(opt("--home") || os.homedir());
  const L = layout(home);
  const src = path.resolve(from, L.bundlePlugin);
  const marker = readJson(path.join(src, MARKER));
  if (!marker || marker.target !== TARGET) return done({ ok: false, error: "not a " + TARGET + " bundle of " + NAME + ": " + src }, 1);
  if (!fs.existsSync(path.join(src, "skills"))) return done({ ok: false, error: "the bundle has no skills folder" }, 1);
  if (TARGET === "codex" && !fs.existsSync(path.join(src, ".codex-plugin", "plugin.json"))) {
    return done({ ok: false, error: "the bundle has no .codex-plugin/plugin.json" }, 1);
  }
  const version = String(marker.sourceVersion || "");
  const inPlace = same(src, L.pluginDir);
  const installed = inPlace ? null : readJson(path.join(L.pluginDir, MARKER));
  const previousVersion = inPlace ? version : installed ? String(installed.sourceVersion || "") : fs.existsSync(L.pluginDir) ? "unknown" : null;

  const stamp = new Date().toISOString().replace(/[-:T]/g, "").slice(0, 14);
  const backupRoot = path.join(home, ".claude-plugin-to-codex", "backups");
  const backup = path.join(backupRoot, [TARGET, NAME, previousVersion || "none", stamp].join("-"));
  const saved = { plugin: false, guard: false, marketplace: false, createdMarketplace: false };
  let marketplaceName = null;

  try {
    if (!inPlace) {
      fs.mkdirSync(backup, { recursive: true });
      if (fs.existsSync(L.pluginDir)) { move(L.pluginDir, path.join(backup, "plugin")); saved.plugin = true; }
      if (L.guard && fs.existsSync(L.guard)) { fs.copyFileSync(L.guard, path.join(backup, "guard.js")); saved.guard = true; }
      if (L.marketplace && fs.existsSync(L.marketplace)) { fs.copyFileSync(L.marketplace, path.join(backup, "marketplace.json")); saved.marketplace = true; }
      move(src, L.pluginDir);
      if (L.guard) {
        const fresh = path.resolve(from, L.bundleGuard);
        if (fs.existsSync(fresh)) { fs.mkdirSync(path.dirname(L.guard), { recursive: true }); fs.copyFileSync(fresh, L.guard); }
        else if (fs.existsSync(L.guard)) fs.rmSync(L.guard, { force: true });
      }
    }
    if (L.marketplace) {
      saved.createdMarketplace = !fs.existsSync(L.marketplace);
      marketplaceName = registerCodex(from, L);
    }
    const placed = readJson(path.join(L.pluginDir, MARKER));
    if (!placed || String(placed.sourceVersion || "") !== version) throw new Error("the plugin in place is not the one just installed");
  } catch (e) {
    const restored = [];
    try {
      if (!inPlace) {
        if (saved.plugin) {
          fs.rmSync(L.pluginDir, { recursive: true, force: true });
          move(path.join(backup, "plugin"), L.pluginDir);
          restored.push("plugin");
        }
        if (L.guard) {
          if (saved.guard) { fs.copyFileSync(path.join(backup, "guard.js"), L.guard); restored.push("guard"); }
          else fs.rmSync(L.guard, { force: true });
        }
      }
      if (L.marketplace) {
        if (saved.marketplace) { fs.copyFileSync(path.join(backup, "marketplace.json"), L.marketplace); restored.push("marketplace"); }
        else if (saved.createdMarketplace) fs.rmSync(L.marketplace, { force: true });
      }
      if (!saved.plugin && !saved.guard && !saved.marketplace) fs.rmSync(backup, { recursive: true, force: true });
    } catch (e2) {
      return done({ ok: false, error: String(e.message || e), restoreError: String(e2.message || e2), backup }, 1);
    }
    return done({ ok: false, error: String(e.message || e), restored }, 1);
  }

  if (!inPlace && !saved.plugin && !saved.guard && !saved.marketplace) fs.rmSync(backup, { recursive: true, force: true });
  pruneBackups(backupRoot);
  const refresh = TARGET === "codex" && !argv.includes("--no-refresh") ? refreshCodex(home, marketplaceName) : null;
  done({
    ok: true,
    target: TARGET,
    name: NAME,
    version,
    previousVersion,
    pluginDir: L.pluginDir,
    backup: saved.plugin ? path.join(backup, "plugin") : null,
    refresh,
    next: TARGET === "codex" ? "Start a new Codex thread so it loads the new version." : "Start a new OpenCode session so it loads the new version.",
  }, 0);
}

main();
`;

/** The installer script for one plugin and one target. */
export function renderInstaller({ target, name, generator = "claude-plugin-port" }) {
  if (target !== "codex" && target !== "opencode") throw new Error(`unknown target ${target}`);
  const values = {
    __TARGET__: JSON.stringify(target),
    __NAME_JSON__: JSON.stringify(name),
    __NAME__: name,
    __HOST__: target === "codex" ? "Codex" : "OpenCode",
    __GENERATOR__: generator,
    __BUNDLE_PLUGIN__: target === "codex" ? `plugins/${name}` : `skills/${name}`,
  };
  return TEMPLATE.replace(/__(TARGET|NAME_JSON|NAME|HOST|GENERATOR|BUNDLE_PLUGIN)__/g, (m) => values[m]);
}
